# 机器人路径编辑器 Docker Compose 配置
version: '3.8'

services:
  # 主应用服务
  app:
    build: .
    container_name: robot-path-editor
    ports:
      - "8080:8080"
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_DSN=./data/robot-path-editor.db
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL 数据库 (可选)
  mysql:
    image: mysql:8.0
    container_name: robot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: robot_paths
      MYSQL_USER: robot
      MYSQL_PASSWORD: robot123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - mysql

volumes:
  mysql_data:

# 使用说明:
# 
# 启动SQLite版本 (推荐):
# docker-compose up -d app
#
# 启动MySQL版本:
# docker-compose --profile mysql up -d
#
# 查看日志:
# docker-compose logs -f app
#
# 停止服务:
# docker-compose down
#
# 完全清理:
# docker-compose down -v