# 机器人路径编辑器 Docker Compose 配置
version: '3.8'

services:
  # 主应用服务
  robot-path-editor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_DSN=root:password@tcp(mysql:3306)/robot_paths?charset=utf8mb4&parseTime=True&loc=Local
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    depends_on:
      - mysql
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - robot-network
    restart: unless-stopped

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: robot_paths
      MYSQL_USER: robot
      MYSQL_PASSWORD: robot123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - robot-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis 缓存 (可选)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - robot-network
    restart: unless-stopped
    profiles:
      - cache

  # Nginx 反向代理 (生产环境)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - robot-path-editor
    networks:
      - robot-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  mysql_data:
  redis_data:

networks:
  robot-network:
    driver: bridge

# 使用说明:
# 
# 开发环境启动:
# docker-compose up -d robot-path-editor mysql
#
# 包含缓存的启动:
# docker-compose --profile cache up -d
# 
# 生产环境启动:
# docker-compose --profile production up -d
#
# 仅启动数据库:
# docker-compose up -d mysql
#
# 查看日志:
# docker-compose logs -f robot-path-editor
#
# 停止所有服务:
# docker-compose down
#
# 完全清理(包括数据):
# docker-compose down -v