// src/services/index.ts
// Barrel file to re-export all API hooks and functions for easier and more reliable import.
// Explicitly importing and re-exporting to ensure robust module resolution.

import {
  useDatabaseConnections,
  useCreateConnection,
  useUpdateConnection,
  useDeleteConnection,
  useTestConnection,
  useTableMappings,
  useCreateMapping,
  useUpdateMapping,
  useDeleteMapping,
  useSyncAllDataFromExternal,
  useValidateExternalTable,
  useNodes,
  useCreateNode,
  useUpdateNode,
  useDeleteNode,
  usePaths,
  useCreatePath,
  useUpdatePath,
  useDeletePath,
  useApplyLayout,
  useGeneratePaths,
  useExportData,
  useHealth,
  useStats,
  useTemplates,
  useCreateTemplate,
  useSaveAsTemplate,
  useApplyTemplate,
  useDeleteTemplate,
  useImportTemplate,
  useExportTemplate,
  usePublicTemplates,
  useTemplatesByCategory,
  useSearchTemplates,
} from '@/services/api'; // Import from the aliased path

export {
  useDatabaseConnections,
  useCreateConnection,
  useUpdateConnection,
  useDeleteConnection,
  useTestConnection,
  useTableMappings,
  useCreateMapping,
  useUpdateMapping,
  useDeleteMapping,
  useSyncAllDataFromExternal,
  useValidateExternalTable,
  useNodes,
  useCreateNode,
  useUpdateNode,
  useDeleteNode,
  usePaths,
  useCreatePath,
  useUpdatePath,
  useDeletePath,
  useApplyLayout,
  useGeneratePaths,
  useExportData,
  useHealth,
  useStats,
  useTemplates,
  useCreateTemplate,
  useSaveAsTemplate,
  useApplyTemplate,
  useDeleteTemplate,
  useImportTemplate,
  useExportTemplate,
  usePublicTemplates,
  useTemplatesByCategory,
  useSearchTemplates,
};
